version: '3.8'

services:
  mysql:
    image: mysql:9.3.0
    container_name: mysql_inventory
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intelligent_inventory_dashboard
    ports:
      - "3306:3306"

  redis:
    image: redis:8.6
    container_name: redis_inventory
    ports:
      - "6379:6379"